import './css/style.css';

// import localFont from "next/font/local";
import { Roboto, Montserrat } from 'next/font/google';

const montserrat = Montserrat({
  weight: ['500', '700', '900'],
  subsets: ['latin'],
  variable: '--font-montserrat',
});

const roboto = Roboto({
  weight: ['400', '700', '900'],
  subsets: ['latin'],
  variable: '--font-roboto',
  display: 'swap'
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable}} ${roboto.variable} font-roboto antialiased bg-slate-100 text-gray-800 tracking-tight`}
      >
        {/* <body className={`${inter.variable} ${hkgrotesk.variable} font-inter antialiased bg-slate-100 text-gray-800 tracking-tight`}> */}
        {/* <body className="font-sans antialiased bg-slate-100 text-gray-800 tracking-tight"> */}
        <div className="flex flex-col min-h-screen overflow-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
